"""Generate per-repository Markdown reports."""

from datetime import datetime
from pathlib import Path

from hackathon_analyzer.core.models import RepoAnalysisResult


def generate_per_repo_report(result: RepoAnalysisResult, output_dir: Path) -> Path:
    """Write a Markdown report for one repo. Returns the output path."""
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / f"{result.meta.slug}-report.md"

    sections = [
        _header_section(result),
        _overview_section(result),
        _structure_section(result),
        _build_section(result),
        _quality_section(result),
        _testing_section(result),
        _architecture_section(result),
        _originality_section(result),
        _promise_reality_section(result),
        _vision_ambition_section(result),
        _tech_stack_section(result),
        _freshness_section(result),
        _ai_integration_section(result),
        _scorecard_section(result),
    ]

    if result.errors:
        sections.append(_errors_section(result))

    sections.append(f"\n---\n*Generated by hackathon-analyzer v0.1.0 on {datetime.now().strftime('%Y-%m-%d %H:%M')}*\n")

    content = "\n".join(sections)
    output_path.write_text(content, encoding="utf-8")
    return output_path


def _score_icon(score_10: float) -> str:
    if score_10 >= 8.0:
        return "🟢"
    elif score_10 >= 6.0:
        return "🟡"
    elif score_10 >= 4.0:
        return "🟠"
    return "🔴"


def _dim_icon(raw: float) -> str:
    if raw >= 0.8:
        return "🟢"
    elif raw >= 0.5:
        return "🟡"
    elif raw >= 0.3:
        return "🟠"
    return "🔴"


def _bar(raw: float, width: int = 12) -> str:
    filled = round(raw * width)
    return "█" * filled + "░" * (width - filled)


def _header_section(r: RepoAnalysisResult) -> str:
    icon = _score_icon(r.total_score)
    lang = r.language.primary_language if r.language else "Unknown"
    date_str = datetime.now().strftime("%Y-%m-%d")
    return (
        f"# Analysis Report: {r.meta.owner}/{r.meta.name}\n\n"
        f"> **Score: {icon} {r.total_score} / 10** | "
        f"Analyzed: {date_str} | "
        f"Language: {lang}\n"
        f">\n"
        f"> Repository: {r.meta.url}\n\n"
        f"---\n"
    )


def _overview_section(r: RepoAnalysisResult) -> str:
    lines = ["## Repository Overview\n"]
    if r.language:
        lang = r.language
        breakdown = " | ".join(f"{k} {v}%" for k, v in list(lang.language_breakdown.items())[:5])
        lines.append(f"- **Primary Language**: {lang.primary_language} ({breakdown})")
        lines.append(f"- **Total LOC**: {lang.total_loc:,} (detection: {lang.detection_method})")
    if r.structure:
        s = r.structure
        lines.append(f"- **Total Files**: {s.total_files} | **Directories**: {s.total_dirs} | **Max Depth**: {s.max_depth}")
        flags = []
        if s.has_src_layout:
            flags.append("src-layout")
        if s.has_tests_dir:
            flags.append("tests dir ✓")
        if s.has_docs_dir:
            flags.append("docs dir ✓")
        if s.has_ci:
            flags.append("CI ✓")
        if s.has_docker:
            flags.append("Docker ✓")
        if flags:
            lines.append(f"- **Features**: {', '.join(flags)}")
    return "\n".join(lines) + "\n"


def _structure_section(r: RepoAnalysisResult) -> str:
    if not r.structure:
        return ""
    s = r.structure
    lines = ["## File Structure (Top Levels)\n"]
    if s.tree_summary:
        lines.append("```")
        lines.append(s.tree_summary)
        lines.append("```")
    if s.layout_patterns:
        lines.append(f"\n**Detected patterns**: {', '.join(s.layout_patterns)}")
    if s.file_extensions:
        top_exts = list(s.file_extensions.items())[:8]
        ext_str = " | ".join(f"`{ext}` ({count})" for ext, count in top_exts)
        lines.append(f"\n**Top extensions**: {ext_str}")
    return "\n".join(lines) + "\n"


def _build_section(r: RepoAnalysisResult) -> str:
    if not r.build:
        return ""
    b = r.build
    lines = ["## Build\n"]
    if b.build_system:
        lines.append(f"- **System**: {b.build_system}")
        lines.append(f"- **Files**: {', '.join(b.build_files_found)}")
    else:
        lines.append("- **System**: Not detected")
        return "\n".join(lines) + "\n"

    if b.build_attempted:
        status = "SUCCESS ✓" if b.build_succeeded else "FAILED ✗"
        dur = f" ({b.build_duration_seconds:.1f}s)" if b.build_duration_seconds else ""
        lines.append(f"- **Result**: {status}{dur}")
        if b.build_output:
            lines.append(f"\n<details><summary>Build output</summary>\n\n```\n{b.build_output[:1500]}\n```\n</details>")
    else:
        lines.append("- **Result**: Not attempted")
    return "\n".join(lines) + "\n"


def _quality_section(r: RepoAnalysisResult) -> str:
    if not r.code_quality:
        return ""
    cq = r.code_quality
    lines = [f"## Code Quality ({cq.language})\n"]
    lines.append(f"- **Linter**: {cq.linter_tool} — {cq.linter_issues} issues")
    if cq.cyclomatic_complexity_avg is not None:
        lines.append(f"- **Cyclomatic Complexity (avg)**: {cq.cyclomatic_complexity_avg:.1f}")
    if cq.maintainability_index_avg is not None:
        lines.append(f"- **Maintainability Index (avg)**: {cq.maintainability_index_avg:.1f}")
    if cq.security_issues_high or cq.security_issues_medium or cq.security_issues_low:
        lines.append(
            f"- **Security (bandit)**: "
            f"{cq.security_issues_high} high / {cq.security_issues_medium} medium / {cq.security_issues_low} low"
        )
    return "\n".join(lines) + "\n"


def _testing_section(r: RepoAnalysisResult) -> str:
    if not r.testing:
        return ""
    t = r.testing
    lines = ["## Testing\n"]
    lines.append(f"- **Test Files**: {t.test_files_count}")
    if t.test_frameworks_detected:
        lines.append(f"- **Frameworks**: {', '.join(t.test_frameworks_detected)}")
    if t.code_loc > 0:
        lines.append(f"- **Test/Code LOC Ratio**: {t.test_to_code_ratio:.1%}")
    lines.append(f"- **CI Test Step**: {'✓' if t.has_ci_test_step else '✗'}")
    return "\n".join(lines) + "\n"


def _architecture_section(r: RepoAnalysisResult) -> str:
    if not r.architecture:
        return ""
    arch = r.architecture
    lines = ["## Architecture\n"]
    if arch.pattern_detected:
        lines.append(f"**Pattern Detected**: {arch.pattern_detected}\n")
    if arch.summary_text:
        lines.append(arch.summary_text + "\n")
    if arch.god_files:
        lines.append("\n**Large files (>500 LOC):**")
        for gf in arch.god_files[:5]:
            lines.append(f"- `{gf}`")
    if arch.top_level_packages:
        lines.append(f"\n**Top-level packages**: {', '.join(arch.top_level_packages)}")
    return "\n".join(lines) + "\n"


def _originality_section(r: RepoAnalysisResult) -> str:
    if not r.originality:
        return ""
    orig = r.originality
    risk_emoji = {"low": "🟢", "medium": "🟡", "high": "🔴"}.get(orig.plagiarism_risk, "⚪")
    lines = ["## Originality\n"]
    lines.append(f"- **Risk Level**: {risk_emoji} {orig.plagiarism_risk.upper()}")
    lines.append(f"- **Snippets Checked**: {orig.snippets_checked} | **GitHub Matches**: {len(orig.matches_found)}")
    if orig.claude_verdict:
        lines.append(f"\n**AI Assessment**:\n\n{orig.claude_verdict}")
    if orig.matches_found:
        lines.append("\n**Matched Repositories:**")
        seen: set[str] = set()
        for m in orig.matches_found[:5]:
            if m.matched_repo not in seen:
                seen.add(m.matched_repo)
                lines.append(f"- [{m.matched_repo}]({m.matched_url})")
    return "\n".join(lines) + "\n"


def _promise_reality_section(r: RepoAnalysisResult) -> str:
    if not r.promise_reality:
        return ""
    pr = r.promise_reality
    icon = _dim_icon(pr.alignment_score)
    lines = ["## Promise vs Reality\n"]
    lines.append(f"- **Alignment Score**: {icon} {pr.alignment_score:.2f} `{_bar(pr.alignment_score)}`")
    if pr.alignment_rationale:
        lines.append(f"\n> {pr.alignment_rationale}\n")
    if pr.claims_supported or pr.claims_unsupported:
        total = pr.claims_supported + pr.claims_unsupported
        lines.append(f"- **Claims**: {pr.claims_supported}/{total} supported")
    if pr.claude_assessment:
        # Truncate very long assessments for readability
        assessment = pr.claude_assessment
        if len(assessment) > 1500:
            assessment = assessment[:1500] + "\n\n*(truncated)*"
        lines.append(f"\n**Assessment**:\n\n{assessment}")
    return "\n".join(lines) + "\n"


def _vision_ambition_section(r: RepoAnalysisResult) -> str:
    if not r.vision_ambition:
        return ""
    va = r.vision_ambition
    icon = _dim_icon(va.vision_score)
    lines = ["## Vision & Ambition\n"]
    lines.append(f"- **Vision Score**: {icon} {va.vision_score:.2f} `{_bar(va.vision_score)}`\n")

    # Sub-dimension breakdown with rationales
    sub_dims = [
        ("Problem Clarity", va.problem_clarity, va.problem_clarity_rationale),
        ("Solution Novelty", va.solution_novelty, va.solution_novelty_rationale),
        ("Scope Ambition", va.scope_ambition, va.scope_ambition_rationale),
        ("Audience Specificity", va.audience_specificity, va.audience_specificity_rationale),
    ]

    lines.append("| Sub-Dimension | Score | Bar | Reasoning |")
    lines.append("|---------------|------:|-----|-----------|")
    for name, val, rationale in sub_dims:
        d_icon = _dim_icon(val)
        reason = rationale[:120] if rationale else ""
        lines.append(f"| {name} | {d_icon} {val:.2f} | `{_bar(val, 10)}` | {reason} |")

    if va.vision_rationale and not va.vision_rationale.startswith("Heuristic"):
        rationale = va.vision_rationale
        if len(rationale) > 1200:
            rationale = rationale[:1200] + "\n\n*(truncated)*"
        lines.append(f"\n**Rationale**:\n\n{rationale}")
    return "\n".join(lines) + "\n"


def _tech_stack_section(r: RepoAnalysisResult) -> str:
    if not r.tech_stack_novelty:
        return ""
    ts = r.tech_stack_novelty
    icon = _dim_icon(ts.novelty_score)
    lines = ["## Tech Stack Novelty\n"]
    lines.append(f"- **Novelty Score**: {icon} {ts.novelty_score:.2f} `{_bar(ts.novelty_score)}`")

    tier_parts = []
    if ts.bleeding_edge_count:
        tier_parts.append(f"🔥 {ts.bleeding_edge_count} bleeding-edge")
    if ts.modern_count:
        tier_parts.append(f"✨ {ts.modern_count} modern")
    if ts.established_count:
        tier_parts.append(f"📦 {ts.established_count} established")
    if ts.legacy_count:
        tier_parts.append(f"⚠️ {ts.legacy_count} legacy")
    if tier_parts:
        lines.append(f"- **Tiers**: {' | '.join(tier_parts)}")

    if ts.cross_domain_bonus:
        lines.append("- **Cross-Domain**: ✓ (bonus applied)")

    if ts.novelty_rationale:
        lines.append(f"\n> {ts.novelty_rationale}\n")

    if ts.notable_deps:
        lines.append("**Notable Dependencies:**")
        for dep in ts.notable_deps[:8]:
            lines.append(f"- {dep}")

    return "\n".join(lines) + "\n"


def _freshness_section(r: RepoAnalysisResult) -> str:
    if not r.hackathon_freshness:
        return ""
    hf = r.hackathon_freshness
    flag_emoji = {"fresh": "🟢", "old": "🔴", "unknown": "⚪"}.get(hf.freshness_flag, "⚪")
    icon = _dim_icon(hf.freshness_score)
    lines = ["## Hackathon Freshness\n"]
    lines.append(f"- **Freshness**: {flag_emoji} **{hf.freshness_flag.upper()}** — {icon} {hf.freshness_score:.2f}")
    if hf.first_commit_date:
        lines.append(f"- **First Commit**: {hf.first_commit_date[:10]}")
    if hf.last_commit_date:
        lines.append(f"- **Last Commit**: {hf.last_commit_date[:10]}")
    if hf.total_commits:
        lines.append(f"- **Total Commits**: {hf.total_commits} | **Span**: {hf.commit_span_days} days")
    if hf.flag_reason:
        lines.append(f"- **Assessment**: {hf.flag_reason}")
    return "\n".join(lines) + "\n"


def _ai_integration_section(r: RepoAnalysisResult) -> str:
    if not r.ai_integration:
        return ""
    ai = r.ai_integration
    if ai.integration_depth == "none":
        return "## AI / LLM Integration\n\n- No AI/LLM integration detected.\n"

    depth_emoji = {
        "basic": "🔵", "intermediate": "🟢", "advanced": "🟡", "expert": "🟣"
    }.get(ai.integration_depth, "⚪")
    icon = _dim_icon(ai.depth_score)
    lines = ["## AI / LLM Integration\n"]
    lines.append(f"- **Depth**: {depth_emoji} **{ai.integration_depth.upper()}** — {icon} {ai.depth_score:.2f}")

    if ai.ai_libraries_detected:
        lines.append(f"- **Libraries**: {', '.join(ai.ai_libraries_detected)}")

    if ai.ai_patterns_detected:
        lines.append(f"- **Patterns**: {', '.join(ai.ai_patterns_detected[:8])}")

    if ai.evidence:
        lines.append("\n**Evidence:**")
        for ev in ai.evidence[:10]:
            lines.append(f"- `{ev}`")

    return "\n".join(lines) + "\n"


def _scorecard_section(r: RepoAnalysisResult) -> str:
    icon = _score_icon(r.total_score)
    lines = ["## Score Breakdown\n"]

    # Visual summary line
    total_bar = _bar(r.total_score / 10.0, width=20)
    lines.append(f"**{icon} Total: {r.total_score} / 10** &nbsp; `{total_bar}` {r.total_score * 10:.0f}%\n")

    # Dimension table with visual bars
    lines.append("| | Dimension | Score | Weight | Progress | Weighted | Notes |")
    lines.append("|:-:|-----------|------:|-------:|----------|--------:|-------|")
    for ds in r.dimension_scores:
        dim_icon = _dim_icon(ds.raw_score)
        bar = _bar(ds.raw_score, width=10)
        pct = f"{ds.weight:.0%}"
        name = ds.name.replace("_", " ").title()
        notes = ds.rationale[:55]
        lines.append(
            f"| {dim_icon} | {name} | {ds.raw_score:.2f} | {pct} "
            f"| `{bar}` {ds.raw_score:.0%} | {ds.weighted_score:.3f} | {notes} |"
        )

    weighted_sum = sum(ds.weighted_score for ds in r.dimension_scores)
    lines.append(f"| {icon} | **TOTAL** | | | | **{weighted_sum:.3f}** | **{r.total_score} / 10** |")
    return "\n".join(lines) + "\n"


def _errors_section(r: RepoAnalysisResult) -> str:
    lines = ["## Analysis Notes (Non-Fatal)\n"]
    for err in r.errors:
        lines.append(f"- {err}")
    return "\n".join(lines) + "\n"
