"""Generate a cross-repository summary Markdown report."""

import re
from datetime import datetime
from pathlib import Path
from statistics import mean, median
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from hackathon_analyzer.core.models import RepoAnalysisResult


def generate_summary_report(results: list, output_dir: Path) -> Path:
    """Write summary report for all analyzed repos (in-memory results). Returns output path."""
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / "summary.md"

    sections = [
        _header(results),
        _leaderboard(results),
        _statistics(results),
        _language_distribution(results),
        _highlights(results),
        _concerns(results),
        _dimension_comparison(results),
        f"\n---\n*Generated by hackathon-analyzer v0.1.0 on {datetime.now().strftime('%Y-%m-%d %H:%M')}*\n",
    ]

    output_path.write_text("\n".join(sections), encoding="utf-8")
    return output_path


def generate_summary_report_from_files(report_files: list[Path], output_dir: Path) -> Path:
    """Build a summary from existing per-repo .md report files on disk.

    Parses each report to extract: repo name, score, language, dimension scores,
    build status, test count, originality risk.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / "summary.md"

    rows = []
    for f in report_files:
        row = _parse_report_file(f)
        if row:
            rows.append(row)

    if not rows:
        output_path.write_text("# Summary\n\nNo valid reports found.\n", encoding="utf-8")
        return output_path

    rows.sort(key=lambda r: r["score"], reverse=True)

    sections = [
        _file_header(rows),
        _file_leaderboard(rows),
        _file_statistics(rows),
        _file_dimension_table(rows),
        f"\n---\n*Generated by hackathon-analyzer v0.1.0 on {datetime.now().strftime('%Y-%m-%d %H:%M')}*\n",
    ]
    output_path.write_text("\n".join(sections), encoding="utf-8")
    return output_path


# ── Parsers ───────────────────────────────────────────────────────────────────

def _parse_report_file(path: Path) -> dict | None:
    """Extract key fields from a per-repo Markdown report."""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None

    # Repo name from H1: # Analysis Report: owner/name
    repo_match = re.search(r"^# Analysis Report: (.+)$", text, re.MULTILINE)
    repo = repo_match.group(1).strip() if repo_match else path.stem.replace("-report", "")

    # Score: e.g. Score: 🟢 8.9 / 10
    score_match = re.search(r"Score:.*?([\d.]+)\s*/\s*10", text)
    score = float(score_match.group(1)) if score_match else 0.0

    # Language
    lang_match = re.search(r"Primary Language\*\*:\s*([^\s(|]+)", text)
    language = lang_match.group(1).strip() if lang_match else "?"

    # LOC
    loc_match = re.search(r"Total LOC\*\*:\s*([\d,]+)", text)
    loc = int(loc_match.group(1).replace(",", "")) if loc_match else 0

    # Files
    files_match = re.search(r"Total Files\*\*:\s*(\d+)", text)
    files = int(files_match.group(1)) if files_match else 0

    # Build
    build_ok = bool(re.search(r"Result\*\*: SUCCESS", text))
    build_system_match = re.search(r"System\*\*:\s*([^\n]+)", text)
    build_system = build_system_match.group(1).strip() if build_system_match else "none"

    # Tests
    test_match = re.search(r"Test Files\*\*:\s*(\d+)", text)
    test_files = int(test_match.group(1)) if test_match else 0
    ci_test = bool(re.search(r"CI Test Step\*\*:\s*✓", text))
    frameworks_match = re.search(r"Frameworks\*\*:\s*([^\n]+)", text)
    frameworks = frameworks_match.group(1).strip() if frameworks_match else ""
    ratio_match = re.search(r"Test/Code LOC Ratio\*\*:\s*([\d.]+)%", text)
    test_ratio = float(ratio_match.group(1)) / 100 if ratio_match else 0.0

    # Originality
    risk_match = re.search(r"Risk Level\*\*:.*?(LOW|MEDIUM|HIGH|UNKNOWN)", text, re.IGNORECASE)
    risk = risk_match.group(1).upper() if risk_match else "UNKNOWN"

    # Dimension scores from the table rows
    dims: dict[str, float] = {}
    # Match table rows like: | 🟢 | Code Quality | 0.77 | 20% | ...
    for m in re.finditer(
        r"\|\s*[🟢🟡🟠🔴]?\s*\|\s*([^|]+?)\s*\|\s*([\d.]+)\s*\|\s*(\d+)%", text
    ):
        dim_name = m.group(1).strip()
        raw = float(m.group(2))
        if dim_name.upper() not in ("TOTAL", "DIMENSION"):
            dims[dim_name] = raw

    # Fallback: parse older plain table format
    if not dims:
        for m in re.finditer(
            r"\|\s*([A-Za-z ]+?)\s*\|\s*([\d.]+)\s*\|\s*\d+%\s*\|", text
        ):
            dim_name = m.group(1).strip()
            raw = float(m.group(2))
            if dim_name.upper() not in ("TOTAL", "DIMENSION"):
                dims[dim_name] = raw

    # Date
    date_match = re.search(r"Generated.*?on\s+(\d{4}-\d{2}-\d{2})", text)
    date = date_match.group(1) if date_match else "?"

    return {
        "repo": repo,
        "score": score,
        "language": language,
        "loc": loc,
        "files": files,
        "build_ok": build_ok,
        "build_system": build_system,
        "test_files": test_files,
        "test_ratio": test_ratio,
        "frameworks": frameworks,
        "ci_test": ci_test,
        "risk": risk,
        "dims": dims,
        "date": date,
        "path": str(path),
    }


# ── File-based summary sections ───────────────────────────────────────────────

def _score_icon(score: float) -> str:
    if score >= 8.0:
        return "🟢"
    elif score >= 6.0:
        return "🟡"
    elif score >= 4.0:
        return "🟠"
    return "🔴"


def _bar(raw: float, width: int = 10) -> str:
    filled = round(raw * width)
    return "█" * filled + "░" * (width - filled)


def _file_header(rows: list[dict]) -> str:
    n = len(rows)
    date_str = datetime.now().strftime("%Y-%m-%d %H:%M")
    return (
        f"# Hackathon Analysis Summary\n\n"
        f"> **Generated**: {date_str} | **Repositories**: {n} | **Tool**: hackathon-analyzer v0.1.0\n\n"
        f"---\n"
    )


def _file_leaderboard(rows: list[dict]) -> str:
    lines = ["## Leaderboard\n"]
    lines.append("| Rank | | Repository | Score | Language | LOC | Build | Tests | CI | Originality | Analyzed |")
    lines.append("|-----:|:-:|------------|------:|----------|----:|:-----:|:-----:|:--:|:-----------:|----------|")

    for rank, r in enumerate(rows, 1):
        medal = {1: "🥇", 2: "🥈", 3: "🥉"}.get(rank, "  ")
        icon = _score_icon(r["score"])
        build = "✓" if r["build_ok"] else "✗"
        tests = f"{r['test_files']}" if r["test_files"] > 0 else "✗"
        ci = "✓" if r["ci_test"] else "✗"
        loc_str = f"{r['loc']:,}" if r["loc"] else "?"
        risk_icon = {"LOW": "🟢", "MEDIUM": "🟡", "HIGH": "🔴"}.get(r["risk"], "⚪")
        lines.append(
            f"| {rank} | {medal} | {r['repo']} | {icon} **{r['score']}** "
            f"| {r['language']} | {loc_str} | {build} | {tests} | {ci} | {risk_icon} {r['risk']} | {r['date']} |"
        )
    return "\n".join(lines) + "\n"


def _file_statistics(rows: list[dict]) -> str:
    scores = [r["score"] for r in rows]
    n = len(rows)
    build_ok = sum(1 for r in rows if r["build_ok"])
    has_tests = sum(1 for r in rows if r["test_files"] > 0)
    risk_counts = {"LOW": 0, "MEDIUM": 0, "HIGH": 0, "UNKNOWN": 0}
    for r in rows:
        risk_counts[r["risk"]] = risk_counts.get(r["risk"], 0) + 1

    avg = mean(scores)
    med = median(scores)
    return (
        f"## Statistics\n\n"
        f"| Metric | Value |\n"
        f"|--------|-------|\n"
        f"| Mean Score | {avg:.1f} / 10 |\n"
        f"| Median Score | {med:.1f} / 10 |\n"
        f"| Highest Score | {max(scores)} |\n"
        f"| Lowest Score | {min(scores)} |\n"
        f"| Build Success | {build_ok}/{n} ({build_ok/n:.0%}) |\n"
        f"| Have Tests | {has_tests}/{n} ({has_tests/n:.0%}) |\n"
        f"| Originality LOW | {risk_counts.get('LOW', 0)} |\n"
        f"| Originality MEDIUM | {risk_counts.get('MEDIUM', 0)} |\n"
        f"| Originality HIGH | {risk_counts.get('HIGH', 0)} |\n"
    )


def _file_dimension_table(rows: list[dict]) -> str:
    # Collect all dimension names seen across all reports
    all_dims: list[str] = []
    seen: set[str] = set()
    for r in rows:
        for d in r["dims"]:
            if d not in seen:
                seen.add(d)
                all_dims.append(d)

    if not all_dims:
        return ""

    lines = ["## Dimension Scores\n"]

    # Header
    header_cols = ["Dimension"] + [r["repo"].split("/")[-1] for r in rows]
    lines.append("| " + " | ".join(header_cols) + " |")
    lines.append("|" + "|".join(["---"] * len(header_cols)) + "|")

    for dim in all_dims:
        row_parts = [dim]
        for r in rows:
            raw = r["dims"].get(dim)
            if raw is not None:
                icon = "🟢" if raw >= 0.8 else ("🟡" if raw >= 0.5 else ("🟠" if raw >= 0.3 else "🔴"))
                row_parts.append(f"{icon} {raw:.2f} `{_bar(raw, 8)}`")
            else:
                row_parts.append("—")
        lines.append("| " + " | ".join(row_parts) + " |")

    return "\n".join(lines) + "\n"


# ── In-memory result sections (used when results are live objects) ─────────────

def _header(results: list) -> str:
    count = len(results)
    date_str = datetime.now().strftime("%Y-%m-%d %H:%M")
    return (
        f"# Hackathon Analysis Summary\n\n"
        f"> **Analyzed**: {date_str} | **Repositories**: {count} | **Tool**: hackathon-analyzer v0.1.0\n\n"
        f"---\n"
    )


def _leaderboard(results: list) -> str:
    sorted_results = sorted(results, key=lambda r: r.total_score, reverse=True)
    lines = ["## Leaderboard\n"]
    lines.append("| Rank | | Repository | Score | Language | Build | Tests | Originality |")
    lines.append("|-----:|:-:|------------|------:|----------|:-----:|:-----:|:-----------:|")
    for rank, r in enumerate(sorted_results, 1):
        lang = r.language.primary_language if r.language else "?"
        build_ok = "✓" if (r.build and r.build.build_succeeded) else "✗"
        has_tests = f"{r.testing.test_files_count}" if (r.testing and r.testing.test_files_count > 0) else "✗"
        risk = r.originality.plagiarism_risk.upper() if r.originality else "?"
        medal = {1: "🥇", 2: "🥈", 3: "🥉"}.get(rank, "")
        icon = _score_icon(r.total_score)
        risk_icon = {"LOW": "🟢", "MEDIUM": "🟡", "HIGH": "🔴"}.get(risk, "⚪")
        lines.append(
            f"| {rank} | {medal} | {r.meta.owner}/{r.meta.name} | {icon} **{r.total_score}** "
            f"| {lang} | {build_ok} | {has_tests} | {risk_icon} {risk} |"
        )
    return "\n".join(lines) + "\n"


def _statistics(results: list) -> str:
    scores = [r.total_score for r in results]
    build_ok = sum(1 for r in results if r.build and r.build.build_succeeded)
    has_tests = sum(1 for r in results if r.testing and r.testing.test_files_count > 0)
    n = len(results)

    risk_counts: dict[str, int] = {"low": 0, "medium": 0, "high": 0, "unknown": 0}
    for r in results:
        risk = (r.originality.plagiarism_risk if r.originality else "unknown")
        risk_counts[risk] = risk_counts.get(risk, 0) + 1

    return (
        f"## Statistics\n\n"
        f"- **Mean Score**: {mean(scores):.1f} | **Median**: {median(scores):.1f} | "
        f"**Min**: {min(scores)} | **Max**: {max(scores)}\n"
        f"- **Build Success Rate**: {build_ok}/{n} ({build_ok/n:.0%})\n"
        f"- **Has Tests**: {has_tests}/{n} ({has_tests/n:.0%})\n"
        f"- **Originality Risk**: "
        f"LOW: {risk_counts['low']} | MEDIUM: {risk_counts['medium']} | HIGH: {risk_counts['high']}\n"
    )


def _language_distribution(results: list) -> str:
    lang_counts: dict[str, int] = {}
    for r in results:
        lang = r.language.primary_language if r.language else "Unknown"
        lang_counts[lang] = lang_counts.get(lang, 0) + 1

    lines = ["## Language Distribution\n"]
    lines.append("| Language | Repos | % of Field |")
    lines.append("|----------|------:|----------:|")
    n = len(results)
    for lang, count in sorted(lang_counts.items(), key=lambda x: -x[1]):
        lines.append(f"| {lang} | {count} | {count/n:.0%} |")
    return "\n".join(lines) + "\n"


def _highlights(results: list) -> str:
    lines = ["## Highlights\n"]

    best_docs = max(results, key=lambda r: r.documentation.doc_score if r.documentation else 0, default=None)
    best_tested = max(results, key=lambda r: r.testing.test_to_code_ratio if r.testing else 0, default=None)
    most_original = min(
        [r for r in results if r.originality],
        key=lambda r: r.originality.similarity_score,
        default=None,
    )

    if best_docs and best_docs.documentation:
        lines.append(f"**Best Documented**: {best_docs.meta.owner}/{best_docs.meta.name} "
                     f"(doc score: {best_docs.documentation.doc_score:.2f})")
    if best_tested and best_tested.testing:
        lines.append(f"\n**Best Tested**: {best_tested.meta.owner}/{best_tested.meta.name} "
                     f"(test ratio: {best_tested.testing.test_to_code_ratio:.1%})")
    if most_original and most_original.originality:
        lines.append(f"\n**Most Original**: {most_original.meta.owner}/{most_original.meta.name} "
                     f"(similarity score: {most_original.originality.similarity_score:.2f})")
    return "\n".join(lines) + "\n"


def _concerns(results: list) -> str:
    lines = ["## Concerns\n"]
    build_failures = [r for r in results if r.build and r.build.build_attempted and not r.build.build_succeeded]
    high_risk = [r for r in results if r.originality and r.originality.plagiarism_risk == "high"]

    if build_failures:
        lines.append("### Build Failures")
        for r in build_failures:
            err = (r.build.build_error or "")[:80] if r.build else ""
            lines.append(f"- **{r.meta.owner}/{r.meta.name}**: {err}")

    if high_risk:
        lines.append("\n### High Plagiarism Risk")
        for r in high_risk:
            matches = len(r.originality.matches_found) if r.originality else 0
            lines.append(f"- **{r.meta.owner}/{r.meta.name}**: {matches} GitHub matches found")

    if not build_failures and not high_risk:
        lines.append("No major concerns detected.")

    return "\n".join(lines) + "\n"


def _dimension_comparison(results: list) -> str:
    lines = ["## Dimension Comparison\n"]
    sorted_results = sorted(results, key=lambda r: r.total_score, reverse=True)

    dim_names = [ds.name for ds in sorted_results[0].dimension_scores] if sorted_results and sorted_results[0].dimension_scores else []

    for dim in dim_names:
        lines.append(f"### {dim.replace('_', ' ').title()}")
        lines.append("| Repository | Score | Notes |")
        lines.append("|------------|------:|-------|")
        for r in sorted_results:
            ds_map = {ds.name: ds for ds in r.dimension_scores}
            ds = ds_map.get(dim)
            if ds:
                lines.append(f"| {r.meta.owner}/{r.meta.name} | {ds.raw_score:.2f} | {ds.rationale[:50]} |")
        lines.append("")

    return "\n".join(lines) + "\n"
